# FM-223: Lista 3

Aluno:  Vinícius Freitas de Almeida

## Exercício 2.1

For each of the following linear maps, decide whether the origin is a sink, source or saddle.

a) $\begin{bmatrix} 4 \quad 30 \\ 1 \quad 3 \end{bmatrix}$
b) $\begin{bmatrix} 1 \quad 1/2 \\ 1/4 \quad 3/4 \end{bmatrix}$
c) $\begin{bmatrix} -0.4 \quad 2.4 \\ -0.4 \quad 1.6 \end{bmatrix}$

## Solução

Por definição, um ponto fixo $p$ é atrator (sink) se existe $\varepsilon > 0$ tal que, para todo ponto $v$ na vizinhança $V_\varepsilon(p)$, existe $n_0 \in \mathbb{N}$ tal que $f^n(v) \in V_\varepsilon(p)$ para todo $n \geq n_0$. 

Com isso em mente, pode-se analisar um mapa linear $f: \mathbb{R}^2 \to \mathbb{R}^2$ a partir dos autovalores de sua matriz associada $A$. Vejamos os pontos fixos de $f$:

$$ f(x) = x \iff A x = x \iff (I - A) x = 0 $$

Se $\det{(I-A)} \neq 0$, i.e. se todos os autovalores de $A$ são diferentes de 1 (nesse caso, $f$ é um mapa linear hiperbólico), então $x = 0$ (vetor nulo) é o único ponto fixo de $f$. Caso contrário, podem existir outros pontos fixos. Exemplo trivial: $A=I$, ou seja, o mapa identidade. Nesse caso, $x = 0$ é um ponto fixo, mas qualquer outro ponto $x \in \mathbb{R}^2$ também é um ponto fixo.

Como a matriz $A$ pode ter autovalores repetidos, é útil usar a forma canônica de Jordan para analisar os pontos fixos de $f$. Seja $J$ a forma canônica de Jordan de $A$, i.e. $J = P^{-1} A P$, onde $P$ é uma matriz invertível. Equivalentemente, $A = P J P^{-1}$. Assim,

$$f^k(x) = A^k x = \left(\prod_{i=1}^{k} P J P^{-1}\right) x = P J^k P^{-1} x$$

No caso particular de matrizes $A \in \mathbb{R}^{2 \times 2}$, a forma canônica de Jordan pode assumir duas possibilidades:

$$ J = \begin{bmatrix} \lambda_1 & 0 \\ 0 & \lambda_2 \end{bmatrix} \quad \text{ou} \quad J = \begin{bmatrix} \lambda & 1 \\ 0 & \lambda \end{bmatrix} $$

E, portanto:

$$ J^k = \begin{bmatrix} \lambda_1^k & 0 \\ 0 & \lambda_2^k \end{bmatrix} \quad \text{ou} \quad J^k = \begin{bmatrix} \lambda^k & k \lambda^{k-1} \\ 0 & \lambda^k \end{bmatrix} $$

Fica fácil perceber que se $ \max\{|\lambda_1|, |\lambda_2|\} < 1$, então a origem será um ponto atrator (sink), pois

$$ \lim_{n \to \infty} J^k = 0 \implies \lim_{n \to \infty} (A^k x) = 0$$

No entanto, se $|\lambda_1| > 1$ e $|\lambda_2| < 1$, então a origem será um ponto de sela (saddle), uma vez que $A$ terá tanto um subespaço vetorial que converge para $0$ e quanto outro que diverge. Por fim, se $|\lambda_1| > 1$ e $|\lambda_2| > 1$, então a origem será um ponto repulsor (source), pois a aplicação iterada de $A$ irá divergir para qualquer $x \in \{\mathbb{R}^2 - \{0\}\}$.

Com tal análise em mente, vamos analisar os autovalores das matrizes na questão:

In [114]:
import numpy as np

def classify_linear_map(a):
    eigvals = np.linalg.eigvals(a)
    print(f"eigenvalues: {eigvals}")
    # magnitude of eigenvalues
    eigvals_abs = np.absolute(eigvals)
    max_l = np.max(eigvals_abs)
    min_l= np.min(eigvals_abs)
    # sink, source or saddle
    if max_l < 1:
        return 'sink'
    elif min_l > 1:
        return 'source'
    elif np.any(eigvals_abs < 1) and np.any(eigvals_abs > 1):
        return 'saddle'
    else:
        return 'unknown'

# a)
a = np.array([[4,30],[1,3]])
print(f"a) {classify_linear_map(a)}")
# b)
b = np.array([[1,1/2],[1/4,3/4]])
print(f"b) {classify_linear_map(b)}")
# c)
c = np.array([[-0.4,-0.4],[2.4,1.6]])
print(f"c) {classify_linear_map(c)}")

eigenvalues: [ 9. -2.]
a) source
eigenvalues: [1.25 0.5 ]
b) saddle
eigenvalues: [0.4 0.8]
c) sink


## Exercício 2.2

Find $$ \lim_{n \to \infty} \begin{bmatrix} 4.5 \quad 8 \\ -2 \quad -3.5 \end{bmatrix}^n \begin{bmatrix} 6 \\ 9 \end{bmatrix}$$

In [115]:
m = np.array([[4.5,8],[-2,-3.5]])
l, q = np.linalg.eig(m)
print(f"eigenvalues: {l}")
print(f"eigenvectors: {q}")

eigenvalues: [0.5 0.5]
eigenvectors: [[ 0.89442719 -0.89442719]
 [-0.4472136   0.4472136 ]]


Como todos os autovalores têm módulo menor que 1, o limite em questão é o vetor nulo 0.

$$ \lim_{n \to \infty} \begin{bmatrix} 4.5 \quad 8 \\ -2 \quad -3.5 \end{bmatrix}^n \begin{bmatrix} 6 \\ 9 \end{bmatrix} = 0$$

## Exercício 2.3

Let $g(x,y) = (x^2 - 5x + y, x^2)$. Find and classify the fixed points of $g$ as sinks, sources or saddles.

## Solução

Usando a definição de ponto fixo:

$$ g(x,y) = (x,y) \iff (x^2 - 5x + y, x^2) = (x,y)$$

Assim, o conjunto $F$ de pontos fixos de $g$ é o subconjunto de $\mathbb{R}^2$ dado por:

$$ F = \{ (x,y) \in \mathbb{R}^2 | x^2 - 6x + y = 0, \quad x^2 - y = 0\} $$

Equivalentemente:

$$ F = \{ (x,y) \in \mathbb{R}^2 | x^2 - 3x = 0, \quad x^2 = y\} = \{ (x,y) \in \mathbb{R}^2 | x (x-3) = 0, \quad y = x^2\}$$

Por fim:

$$ F = \{ (0,0), (3,9) \} $$

Jacobiana de $g$:

$$ Dg(x,y) = \begin{bmatrix} 2x - 5 & 1 \\ 2x & 0 \end{bmatrix}$$

Para $(0,0)$:

$$ Dg(0,0) = \begin{bmatrix} -5 & 1 \\ 0 & 0 \end{bmatrix}$$

Autovalores $\lambda_1 = 0$ e $\lambda_2 = -5$. Como $|\lambda_1| < 1$ e $|\lambda_2| > 1$, $(0,0)$ é um ponto de sela.

Para $(3,9)$:

$$ Dg(3,9) = \begin{bmatrix} 1 & 1 \\ 12 & 0 \end{bmatrix}$$

Autovalores $\lambda_1 = 4$ e $\lambda_2 = -3$. Como $|\lambda_1| > 1$ e $|\lambda_2| > 1$, $(3,9)$ é um ponto repulsor.

## Exercício 2.4

Find and classify all fixed points and period-two orbits of the Hénon map with

a) $a = -0.56$ and $b = -0.5$

b) $a = 0.21$ and $b = 0.6$

## Solução

O mapa de Hénon é dado por:

$$ f_{a,b}(x,y) = (a-x^2+by,x) $$

Para achar os pontos fixos, basta resolver:

$$ f_{a,b}(x,y) = (x,y) \iff (a-x^2+by,x) = (x,y) \iff a-x^2+by = x \text{ e } x = y $$

Assim, o conjunto $F$ de pontos fixos de $f_{a,b}$ é o subconjunto de $\mathbb{R}^2$ dado por:

$$ F = \{ (x,y) \in \mathbb{R}^2 | x^2 + (1-b)x -a = 0 \text{ e } x = y \} $$

A equação quadrática resulta em:

$$ x = \frac{b-1 \pm \sqrt{(1-b)^2 + 4a}}{2} $$

Jacobiana de $f_{a,b}$:

$$ Df_{a,b}(x,y) = \begin{bmatrix} -2x & b \\ 1 & 0 \end{bmatrix}$$

Para encontrar as órbitas de período 2, é preciso resolver $f^2_{a,b}(x,y) = (x,y)$:

$$ (x,y) \underbrace{\mapsto}_f (a-x^2+by,x) \underbrace{\mapsto}_f (-a^2 - 2 a b y + 2 a x^2 + a - b^2 y^2 + 2 b x^2 y + b x - x^4,a-x^2+by) $$

Assim, é preciso resolver o sistema:

$$ \begin{cases} -a^2 - 2 a b y + 2 a x^2 + a - b^2 y^2 + 2 b x^2 y + b x - x^4 = x \\ a-x^2+by = y \end{cases} $$

No entanto, é preciso remover os dois pontos fixos obtidos anteriormente, pois eles são órbitas de período 1.

A resposta será desenvolvida usando a biblioteca `sympy` do Python. Porém, evidentemente, é possível resolver o sistema acima usando manipulações algébricas (uma delas seria notar que o polinômio do quarto grau pode ser reduzido para segundo grau, uma vez que 2 de suas raízes estão contempladas pelos pontos fixos).

In [116]:
from sympy import *

a, b, x, y = symbols('a b x y', real=True)

# Solve for (x,y) to obtain candidate solutions for f^2(x,y) = (x,y)
eq1 = Eq(x, -a**2 - 2*a*b*y + 2*a*x**2 + a - b**2*y**2 + 2*b*x**2*y + b*x - x**4)
eq2 = Eq(y, a-x**2+b*y)

In [117]:
eq1

Eq(x, -a**2 - 2*a*b*y + 2*a*x**2 + a - b**2*y**2 + 2*b*x**2*y + b*x - x**4)

In [118]:
eq2

Eq(y, a + b*y - x**2)

In [119]:
from IPython.display import display, Math
soln = solve([eq1, eq2], [x, y])
print("Candidates for solution: ")
display(Math(latex(soln)))

Candidates for solution: 


<IPython.core.display.Math object>

In [120]:
# remove fixed points of f
print("Solution: ")
display(Math(latex(soln[:2])))

Solution: 


<IPython.core.display.Math object>

In [121]:
def henon_fixed_points(a,b):
    delta = np.sqrt((1-b)**2 + 4*a)
    x1 = (1-b + delta)/2
    x2 = (1-b - delta)/2
    return [(x1,x1), (x2,x2)]

def henon_jacobian(b, x):
    return np.array([[-2*x, b],[1, 0]])



### Item a)

Pontos fixos:

In [122]:
av = -0.56
bv = -0.5
henon_fixed_points(av,bv)

[(0.7999999999999995, 0.7999999999999995),
 (0.7000000000000005, 0.7000000000000005)]

Da matriz Jacobiana, podemos classificar cada um dos dois pontos fixos:

In [123]:
for x,_ in henon_fixed_points(av,bv):
    print(f"Jacobian at fixed point ({x}, {x}):")
    m = henon_jacobian(bv, x)
    print(m)
    c = classify_linear_map(m)
    print(f"Fixed point classification: {c}")

Jacobian at fixed point (0.7999999999999995, 0.7999999999999995):
[[-1.6 -0.5]
 [ 1.   0. ]]
eigenvalues: [-1.17416574 -0.42583426]
Fixed point classification: saddle
Jacobian at fixed point (0.7000000000000005, 0.7000000000000005):
[[-1.4 -0.5]
 [ 1.   0. ]]
eigenvalues: [-0.7+0.1j -0.7-0.1j]
Fixed point classification: sink


Órbitas de período 2:

In [124]:
# a) $a = -0.56$ and $b = -0.5$
Subs(soln[0], (a,b), (-Rational(56,100), -Rational(1,2)))

Subs((-b/2 - sqrt(4*a - 3*b**2 + 6*b - 3)/2 + 1/2, -b/2 + sqrt(4*a - 3*b**2 + 6*b - 3)/2 + 1/2), (a, b), (-14/25, -1/2))

In [125]:
Subs(soln[1], (a,b), (-Rational(56,100), -Rational(1,2))).doit()

(3/4 + sqrt(899)*I/20, 3/4 - sqrt(899)*I/20)

Como as soluções das equações não pertencem a $\mathbb{R}^2$, podemos afirmar que $f_{a,b}$ não possui órbitas de período 2 para $a = -0.56$ and $b = -0.5$.

### Item b)

Pontos fixos:

In [126]:
av = 0.21
bv = 0.6
henon_fixed_points(av,bv)

[(0.7, 0.7), (-0.3, -0.3)]

Da matriz Jacobiana, podemos classificar cada um dos dois pontos fixos:

In [127]:
for x,_ in henon_fixed_points(av,bv):
    print(f"Jacobian at fixed point ({x}, {x}):")
    m = henon_jacobian(bv, x)
    print(m)
    c = classify_linear_map(m)
    print(f"Fixed point classification: {c}")

Jacobian at fixed point (0.7, 0.7):
[[-1.4  0.6]
 [ 1.   0. ]]
eigenvalues: [-1.74403065  0.34403065]
Fixed point classification: saddle
Jacobian at fixed point (-0.3, -0.3):
[[0.6 0.6]
 [1.  0. ]]
eigenvalues: [ 1.13066239 -0.53066239]
Fixed point classification: saddle


Órbitas de período 2:

In [128]:
# b) $a = 0.21$ and $b = 0.6$
Subs(soln[0], (a,b), (Rational(21,100), Rational(6,10))).doit()

(-1/10, 1/2)

In [129]:
Subs(soln[1], (a,b), (Rational(21,100), Rational(6,10))).doit()

(1/2, -1/10)

## Exercício 2.5

Let $f(x,y,z)=(x^2 y, y^2, xz + y)$ be a map on $\mathbb{R}^3$. Find and classify all the fixed points of $f$.

## Solução

Para achar os pontos fixos de $f(x,y,z)=(x^2 y, y^2, xz + y)$, é preciso resolver o sistema:

$$ \begin{cases} x^2 y = x \\ y^2 = y \\ xz + y = z \end{cases} $$

- Da segunda equação, $y = 0$ ou $y = 1$.
- Se $y = 0$, então $x = z = 0$ (ponto fixo trivial).
- Se $y = 1$, então:
    - $x = 0$ e $z = 1$
    - ou $x = 1$ e $z = 2$

Logo, existem 3 pontos fixos:

$$ F = \{ (0,0,0), (0,1,1), (1,1,2) \} $$

Jacobiana de $f$:

$$ Df(x,y,z) = \begin{bmatrix} 2xy & x^2 & 0 \\ 0 & 2y & 0 \\ z & 1 & x \end{bmatrix}$$

In [130]:
def jacobian(x, y, z):
    return np.array([[2*x*y, x**2, 0],[0, 2*y, 0],[z, 1, x]])

In [131]:
for x in {(0,0,0), (0,1,1), (1,1,2)}:
    print(f"Jacobian at fixed point {x}:")
    m = jacobian(*x)
    print(m)
    c = classify_linear_map(m)
    print(f"Fixed point classification: {c}")

Jacobian at fixed point (0, 0, 0):
[[0 0 0]
 [0 0 0]
 [0 1 0]]
eigenvalues: [0. 0. 0.]
Fixed point classification: sink
Jacobian at fixed point (0, 1, 1):
[[0 0 0]
 [0 2 0]
 [1 1 0]]
eigenvalues: [0. 0. 2.]
Fixed point classification: saddle
Jacobian at fixed point (1, 1, 2):
[[2 1 0]
 [0 2 0]
 [2 1 1]]
eigenvalues: [1. 2. 2.]
Fixed point classification: unknown
